"""ε-3 tuning sweep — push converted-stream CER toward 20%.

Reuses the audio generated by ``eps3_semantic_vc_test.py``:
  outputs/eps3_semantic_vc/speaker_donor_{emo}_rep{N}.wav   (F1 attempts at zh)
  outputs/eps3_semantic_vc/content_donor_{emo}_rep{N}.wav   (native ref attempts at zh)

Sweeps two knn-VC dials and one matching-set composition:

  topk                   ∈ {1, 2, 4, 8, 16}
  matching_set_size      ∈ {SMALL = jvnv ref + 8 F1 attempts (same emo)
                            MEDIUM = jvnv refs × 6 emo + F1 attempts × 3 emo
                            LARGE  = MEDIUM + extra F1 self-clones in JP
                                     for additional speaker-only diversity}
  prematched (vocoder)   ∈ {True, False}

Plus a content-donor selection pass: out of the 8 native-ref attempts
per emotion, pick the one whose own CER is lowest (= cleanest native
pronunciation) before VC. This isolates what VC quality alone can do.
"""
from __future__ import annotations
import os, sys, json, statistics
from pathlib import Path

import numpy as np
import torch
import soundfile as sf

sys.path.insert(0, "src")
sys.path.insert(0, "upstream/knn-vc")

from ovet.analyzers.asr_analyzer import ASRAnalyzer                            # noqa: E402
from ovet.utils.io import save_wav                                             # noqa: E402
from ovet.evaluation.zh_eval import (                                          # noqa: E402
    aggregate_zh_cell, format_cell_row, cer_zh,
)


JVNV_DIR        = Path("baseline/jvnv_samples")
EPS3_DIR        = Path("outputs/eps3_semantic_vc")
OUT_DIR         = Path("outputs/eps3_tune")
ZH_HANZI        = "明天的天气预报是多云转晴。"
SR_OMNI         = 24000
SR_KNN          = 16000
EMOTIONS        = ["sad", "happy", "anger"]
ALL_EMOTIONS    = ["anger", "disgust", "fear", "happy", "sad", "surprise"]
REPS            = 8

TOPKS           = [1, 2, 4, 8, 16]
MATCHING_SET    = ["small", "medium", "large"]
PREMATCHED      = [True, False]


def _resample(audio: np.ndarray, src_sr: int, dst_sr: int) -> np.ndarray:
    if src_sr == dst_sr:
        return audio
    import librosa
    return librosa.resample(audio.astype(np.float32),
                            orig_sr=src_sr, target_sr=dst_sr)


def _to_16k_temp(src: Path, cache_dir: Path) -> Path:
    """Cache-aware resampling to 16 kHz (knn-VC wants this)."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    out = cache_dir / f"_16k_{src.stem}.wav"
    if out.exists():
        return out
    audio, sr = sf.read(src)
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    audio_16k = _resample(audio, sr, SR_KNN)
    sf.write(out, audio_16k, SR_KNN)
    return out


def _build_matching_set(emo: str, kind: str, cache_dir: Path) -> list[Path]:
    """Return list of 16 kHz wav paths for the F1 matching pool."""
    paths: list[Path] = []
    if kind == "small":
        # current default: jvnv ref + 8 F1 attempts in zh (same emo)
        paths.append(JVNV_DIR / f"jvnv_F1_{emo}.wav")
        for rep in range(REPS):
            paths.append(EPS3_DIR / f"speaker_donor_{emo}_rep{rep}.wav")
    elif kind == "medium":
        # All 6 emotion refs + 8 attempts × 3 emos already on disk
        for e in ALL_EMOTIONS:
            p = JVNV_DIR / f"jvnv_F1_{e}.wav"
            if p.exists():
                paths.append(p)
        for e in EMOTIONS:        # only emos we've generated for
            for rep in range(REPS):
                paths.append(EPS3_DIR / f"speaker_donor_{e}_rep{rep}.wav")
    elif kind == "large":
        # MEDIUM + every F1 self-clone we have on disk anywhere
        # (disentanglement_v2/clones contains F1_*_ja, F1_*_en, etc.)
        for e in ALL_EMOTIONS:
            p = JVNV_DIR / f"jvnv_F1_{e}.wav"
            if p.exists():
                paths.append(p)
        for e in EMOTIONS:
            for rep in range(REPS):
                paths.append(EPS3_DIR / f"speaker_donor_{e}_rep{rep}.wav")
        for p in sorted(Path("outputs/disentanglement_v2/clones").glob("F1_*.wav")):
            paths.append(p)
    else:
        raise ValueError(kind)

    # Resample everything to 16 kHz once
    return [_to_16k_temp(p, cache_dir) for p in paths if p.exists()]


def _content_donor_cers(asr: ASRAnalyzer, emo: str) -> dict[int, float]:
    """Per-rep CER of the native-ref content donors. Used to pick the
    cleanest donor for the 'best' content selection variant."""
    out = {}
    for rep in range(REPS):
        path = EPS3_DIR / f"content_donor_{emo}_rep{rep}.wav"
        hyp = asr.transcribe(path, language="zh")
        out[rep] = cer_zh(ZH_HANZI, hyp)
    return out


def main():
    os.environ.setdefault("HF_HOME", "/workspace/hf_cache")
    os.environ.setdefault("TORCH_HOME", "/workspace/hf_cache/torch")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cache16 = OUT_DIR / "_cache_16k"

    print("[ε3-tune] loading ASR + knn-VC ...", flush=True)
    asr = ASRAnalyzer()
    from hubconf import knn_vc                                                 # noqa: E402
    knnvcs = {pm: knn_vc(pretrained=True, prematched=pm, device="cuda")
              for pm in PREMATCHED}

    # Pre-compute content-donor CERs to identify the best donor per emo.
    print("\n[ε3-tune] scoring content donors ...", flush=True)
    best_donor_per_emo: dict[str, int] = {}
    for emo in EMOTIONS:
        cd_cers = _content_donor_cers(asr, emo)
        best_donor_per_emo[emo] = min(cd_cers, key=cd_cers.get)
        print(f"  {emo}: best rep={best_donor_per_emo[emo]} "
              f"(CER={cd_cers[best_donor_per_emo[emo]]:.3f}); "
              f"all={ {k: f'{v:.2f}' for k, v in cd_cers.items()} }",
              flush=True)

    # Pre-build matching sets (cached features keyed by composition+vocoder).
    print("\n[ε3-tune] building matching sets ...", flush=True)
    matching_sets: dict[tuple[str, str, bool], object] = {}
    for kind in MATCHING_SET:
        for emo in EMOTIONS:
            paths = _build_matching_set(emo, kind, cache16)
            for pm in PREMATCHED:
                key = (kind, emo, pm)
                matching_sets[key] = (
                    knnvcs[pm].get_matching_set([str(p) for p in paths]),
                    len(paths),
                )
    for (kind, emo, pm), (_, n) in matching_sets.items():
        if pm == PREMATCHED[0]:
            print(f"  {kind}/{emo}: {n} F1 wavs", flush=True)

    # Sweep cells.
    rows = []
    print(f"\n[ε3-tune] sweeping {len(MATCHING_SET) * len(TOPKS) * len(PREMATCHED)} "
          f"× {len(EMOTIONS)} × {REPS} reps "
          f"= {len(MATCHING_SET) * len(TOPKS) * len(PREMATCHED) * len(EMOTIONS) * REPS} VC calls",
          flush=True)

    flat_cers: dict[str, list[float]] = {}
    for kind in MATCHING_SET:
        for pm in PREMATCHED:
            for topk in TOPKS:
                cell_name = f"{kind}_pm{int(pm)}_k{topk}"
                cers_cell = []
                for emo in EMOTIONS:
                    matching, _ = matching_sets[(kind, emo, pm)]
                    hyps = []
                    for rep in range(REPS):
                        content_path = EPS3_DIR / f"content_donor_{emo}_rep{rep}.wav"
                        content_16k = _to_16k_temp(content_path, cache16)
                        query_seq = knnvcs[pm].get_features(str(content_16k))
                        converted = knnvcs[pm].match(
                            query_seq, matching, topk=topk,
                        ).cpu().numpy()
                        converted_24k = _resample(converted, SR_KNN, SR_OMNI)
                        out_wav = OUT_DIR / f"{cell_name}_{emo}_rep{rep}.wav"
                        save_wav(out_wav, converted_24k, SR_OMNI)
                        hyps.append(asr.transcribe(out_wav, language="zh"))
                    stats = aggregate_zh_cell(hyps, ZH_HANZI)
                    rows.append({"cell": cell_name, "emotion": emo,
                                 "stats": stats.__dict__})
                    cers_cell.extend([cer_zh(ZH_HANZI, h) for h in hyps])
                flat_cers[cell_name] = cers_cell
                med = statistics.median(cers_cell)
                q1  = statistics.quantiles(cers_cell, n=4)[0]
                q3  = statistics.quantiles(cers_cell, n=4)[2]
                print(f"  {cell_name:<22} cer_med={med:.3f}  "
                      f"q1={q1:.3f}  q3={q3:.3f}  σ={statistics.pstdev(cers_cell):.3f}",
                      flush=True)

    # Best-content-donor variant: re-run with the lowest-CER content
    # donor per emotion (still picking the same matching set / topk
    # that won above for this is decided after seeing the sweep).
    print("\n=== top-10 cells (by median CER, lower is better) ===", flush=True)
    sorted_cells = sorted(flat_cers.items(), key=lambda kv: statistics.median(kv[1]))
    for name, cers in sorted_cells[:10]:
        med = statistics.median(cers)
        gap = (med - 0.20) * 100
        print(f"  {name:<24} cer_med={med:.3f}  gap_to_20={gap:+.1f}pp", flush=True)

    # Run the winner with best-content-donor and 16 reps total
    winner_name = sorted_cells[0][0]
    print(f"\n[ε3-tune] re-running winner '{winner_name}' with best content donor ...",
          flush=True)
    parts = winner_name.split("_")
    win_kind = parts[0]
    win_pm   = bool(int(parts[1].lstrip("pm")))
    win_topk = int(parts[2].lstrip("k"))
    bc_cers = []
    for emo in EMOTIONS:
        matching, _ = matching_sets[(win_kind, emo, win_pm)]
        best_rep = best_donor_per_emo[emo]
        content_path = EPS3_DIR / f"content_donor_{emo}_rep{best_rep}.wav"
        content_16k = _to_16k_temp(content_path, cache16)
        # 8 different VC rolls of the same source: deterministic actually,
        # so just one pass per emotion is enough for "best content".
        query_seq = knnvcs[win_pm].get_features(str(content_16k))
        converted = knnvcs[win_pm].match(
            query_seq, matching, topk=win_topk,
        ).cpu().numpy()
        converted_24k = _resample(converted, SR_KNN, SR_OMNI)
        out_wav = OUT_DIR / f"_BEST_{winner_name}_{emo}.wav"
        save_wav(out_wav, converted_24k, SR_OMNI)
        hyp = asr.transcribe(out_wav, language="zh")
        cer = cer_zh(ZH_HANZI, hyp)
        bc_cers.append(cer)
        print(f"  {emo}: cer={cer:.3f}  hyp={hyp[:70]}", flush=True)
    print(f"  best-content cer median over {len(bc_cers)} emotions = "
          f"{statistics.median(bc_cers):.3f}", flush=True)

    with open(OUT_DIR / "result.json", "w", encoding="utf-8") as f:
        json.dump({
            "rows": rows,
            "winner": winner_name,
            "winner_best_content": {"emos": EMOTIONS, "cers": bc_cers},
            "config": {
                "topks": TOPKS, "matching_sets": MATCHING_SET,
                "prematched": PREMATCHED, "emotions": EMOTIONS, "reps": REPS,
            },
        }, f, indent=2, ensure_ascii=False)
    print(f"\n[ε3-tune] saved -> {OUT_DIR}", flush=True)


if __name__ == "__main__":
    main()
